### ISSUE TITLE
Setup starter with optional keys in application.yaml

### ISSUE THREAD

**Issue by clun** [ff4j/ff4j-spring-boot-starter-parent#106]
**Is your feature request related to a problem? Please describe.**
When you  importing the `spring-boot-starter` in your application you may asking yourself what are the beans you should create and which ones are already available. As far as I understand: 
- you need to define `ff4j`
- you need to define and expose the `web console` if you want it (`FF4jDispatcherServlet`)
- The rest Api is always there but you can enable the swagger doc with a an annotation.

**Describe the solution you'd like**
What about creating dedicated keys in the `application.yaml` for ff4j enabling or disabling some beans. Also we can secure the web-console with login/password out of the box with spring security. This is what it look like :
```yaml
ff4j:
  webconsole:
    enable: true
    url: /ff4j-web-console
    secure: true
    username: admin
    password: ff4j
  rest-api:
    enable: true 
    url: /api/ff4j
    secure: true
    username: admin
    password: ff4j
```
I have created a working sample for the web-console part [here](https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-secured-console)

I also IMO module `ff4j-web` should be a dependency of the starter. You can still exclude if you don't want it but must of people using the starter what the we console.

With that perspective, only the `ff4j` bean is required in your app everything else is configuration. FF4j is such a complex object with different stores and properties that for now i don't see it yaml but later what about a constructor with a yaml in the ff4j object.

**Comment by paul58914080** [comment]
Hello @clun ,

I would have something like this for the configuration

```yaml
ff4j:
  security:
    username: admin
    password: ff4j   
  web-console:
   url: /ff4j-web-console # default is '/ff4j-web-console'
  rest-api:
    enable-swagger: true # default is 'true'
```

- just having `rest-api.enable` kind of misleads whether or not Restful web api is enabled or not. Whereas we want to have swagger to be enabled or not
- Not sure the reason of having `rest-api.url`, so I have removed it. 
- `secure` seemed redundant between `web-console` and `rest-api` hence made it common and removed `enable` property as I would be conditionally evaluating it based on `username` and `password`

Let me know what you think.

**Comment by clun** [comment]
I think if it very good. 

- You want the  rest API to be always UP and that make sense in a spring boot starter.
- The settings you put are only for the Spring boot starter itself.. all good.

I got additional idea here (Optional). 
- Should we also consider other properties in the YAML ? like 
[config](https://github.com/ff4j/ff4j/blob/master/ff4j-test/src/main/resources/test-ff4j-features.yml). I said it because most of the work is already done in [ff4j-config-yaml](https://github.com/ff4j/ff4j/tree/master/ff4j-config-yaml) 

https://github.com/ff4j/ff4j/blob/master/ff4j-config-yaml/src/test/java/org/ff4j/parser/yaml/YamlParserTest.java

```java
InputStream ymlFile = getClass().getClassLoader().getResourceAsStream("application.yml");
FF4jConfiguration ymlConfig = new YamlParser().parseConfigurationFile(ymlFile);
```

Thanks

**Comment by paul58914080** [comment]
I think is it a very good idea to consider `ff4j-yaml-config`. I need to further deep dive into it. However in this issue I will first try to target only the following configurations

- Configuring spring security username and password
- Configuring web console with context path
- Configuring enable or disable swagger 

For `ff4j-config` I have raised a new issue https://github.com/ff4j/ff4j-spring-boot-starter-parent/issues/236 which we will track and implement

**Comment by paul58914080** [comment]
Implemented enabling and disabling of springdoc with #245 

```yaml
ff4j:
  springdoc:
    enable: true # default is 'false'
```

**Comment by paul58914080** [comment]
Implemented enabling and disabling of audit with https://github.com/ff4j/ff4j-spring-boot-starter-parent/pull/254/files

```yaml
ff4j:
  audit:
    enabled: true # default is false
```

**Comment by paul58914080** [comment]
Implemented enabling and disabling of web-console with context-path with https://github.com/ff4j/ff4j-spring-boot-starter-parent/pull/255

```yaml
ff4j:
  web-console:
    enabled: true # default is 'false'
    context-path: /ff4j-web # default is '/ff4j-web-console'
```

**Comment by paul58914080** [comment]
Final configuration looks like this with https://github.com/ff4j/ff4j-spring-boot-starter-parent/pull/260

```yml
ff4j:
  api:
    context-path: /api/v1/ff4j     # default '/api/ff4j'
    spring-doc:
      enabled: true                # default 'false'
  audit:
    enabled: true                  # default 'false'
  security:
    enabled: true                  # default 'false'
  web-console:
    context-path: /ff4j-web        # default '/ff4j-web-console'
    enabled: true                  # default 'false'
    security:
      enabled: true                # default 'false'
      username: admin              # default 'admin'
      password: admin              # default 'admin'
```
